-- Functional verification for 202608040057_seva_points_eligibility.sql.
--
-- Rolled back at the end. Every local is prefixed v_ so it can never shadow a
-- column name. Anything that must be refused is attempted as the devotee who
-- would really attempt it, under `set local role authenticated`, so the row
-- level security policies, the column grants and the permission checks are what
-- is being tested rather than superuser rights waving everything through.
--
-- ---------------------------------------------------------------------------
-- What is being proved.
--
-- The temple's sentence is a conjunction of three things, and the whole point
-- of this file is that it is a conjunction: completed AND verified AND served.
-- So section 2 does not check the six cases somebody thought of. It walks the
-- entire cross product — five assignment statuses by four attendance values by
-- four verification levels, eighty combinations — and asserts three invariants
-- over all eighty at once:
--
--   counted        exactly when status is completed, attendance is served, and
--                  verification is live_timer, qr_scan or member_verified
--   not_served     exactly when somebody said they were not there
--   awaiting_*     everything else, and never anything else
--
-- Stated that way, a mutation that widens the rule by one value fails, and it
-- fails whether or not anybody thought to write a case for that value.
--
-- The cast, and what each one is for:
--
--   poster    ...01  posts the ordinary seva; may verify and confirm it
--   president ...02  app.view_all; the only authority over weekly seva
--   alldone   ...03  completed + member_verified + served. Earns. Also carries
--                    a pending act, a custom-named seva, a January act and two
--                    gifts, so the windows and the breakdown have something to
--                    be wrong about
--   unmarked  ...04  everything but the attendance mark. THE row this feature
--                    exists for: zero points, and told so in words
--   absent    ...05  marked absent
--   excused   ...06  marked excused
--   selfsaid  ...07  completed and served, but only they say it happened
--   unclosed  ...08  verified and served on a seva nobody closed out
--   noshow    ...09  marked served on an assignment recorded as a no-show
--   weekly    ...10  recurring seva, generated by the real generator from a
--                    real template, taken through the real RPCs
--   timer     ...11  a live timer nobody stopped, since confirmed: 0.7, not 0
--   orphan    ...12  a pending act on a seva with no poster, so the President's
--                    queue can be proved wider than the poster's
--   other     ...13  an ordinary devotee with no seva at all, who must be able
--                    to read nothing about anybody
--   soloist   ...15  posts a seva and serves it themselves, which is what the
--                    live timer does on every act it creates. Holds the
--                    authority over their own seva and must still not be the
--                    someone in "someone verified it"
--   capped    ...14  ten hours in one Chicago day against an eight-hour cap,
--                    plus one act still waiting. The waiting act must spend no
--                    cap at all: if it did, confirming Thursday's seva would
--                    silently move Tuesday's credit down
--
-- The final row must read: seva points eligibility verification passed

begin;

-- ---------------------------------------------------------------------------
-- 0. The ground.
-- ---------------------------------------------------------------------------

do $$
declare
  v_source text;
begin
  if to_regprocedure('public.seva_points_status(text, text, text)') is null
    or to_regprocedure('public.seva_points_note(text)') is null
    or to_regprocedure('public.verify_seva_assignment(uuid)') is null
    or to_regprocedure('public.my_seva_profile()') is null
    or to_regprocedure('public.my_seva_breakdown()') is null
    or to_regprocedure('public.my_seva_acts(date, date)') is null
    or to_regprocedure('public.list_seva_awaiting_confirmation(date, date)') is null
  then
    raise exception 'The seva points eligibility functions are not all present.';
  end if;

  -- Exactly one my_seva_mala and exactly one seva_mala_acts. A leftover
  -- overload with a defaulted argument is ambiguous rather than merely stale.
  if (select count(*) from pg_proc join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
      where pg_namespace.nspname = 'public' and pg_proc.proname = 'my_seva_mala') <> 1
  then
    raise exception 'my_seva_mala has more than one overload.';
  end if;
  if (select count(*) from pg_proc join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
      where pg_namespace.nspname = 'public' and pg_proc.proname = 'seva_mala_acts') <> 1
  then
    raise exception 'seva_mala_acts has more than one overload.';
  end if;

  -- The 0.6 branch is gone, not merely unreachable.
  v_source := pg_get_functiondef('public.seva_mala_acts(uuid)'::regprocedure);
  if position('0.6' in v_source) > 0 then
    raise exception 'seva_mala_acts still carries a 0.6 multiplier.';
  end if;
  if position('seva_points_status' in v_source) = 0 then
    raise exception 'seva_mala_acts does not decide eligibility through seva_points_status.';
  end if;

  -- The components stay unreadable. 0055 section 4 is not defence in depth, it
  -- is the whole of the defence, and nothing added here may have widened it.
  if has_table_privilege('authenticated', 'public.period_scores', 'select')
    or has_table_privilege('authenticated', 'public.seva_mala_periods', 'select')
  then
    raise exception 'authenticated can read the Seva Mala components.';
  end if;
  if has_function_privilege('authenticated', 'public.seva_mala_acts(uuid)', 'execute') then
    raise exception 'authenticated can call seva_mala_acts directly.';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 1. The rule, over its entire domain.
--
--    Eighty combinations, three invariants. The expectations are written as the
--    temple's sentence rather than as a copy of the function's branches, so a
--    reordering that changes an answer is caught by the third invariant and a
--    widening by the first.
-- ---------------------------------------------------------------------------

do $$
declare
  v_status text;
  v_attendance text;
  v_verification text;
  v_result text;
  v_should_count boolean;
  v_should_refuse boolean;
  v_seen integer := 0;
begin
  foreach v_status in array array[
    'assigned', 'confirmed', 'completed', 'no_show', 'withdrawn'
  ] loop
    foreach v_attendance in array array['served', 'absent', 'excused', '(null)'] loop
      foreach v_verification in array array[
        'self_report', 'live_timer', 'qr_scan', 'member_verified'
      ] loop
        v_seen := v_seen + 1;
        v_result := public.seva_points_status(
          v_status, nullif(v_attendance, '(null)'), v_verification
        );

        -- The temple's sentence, restated: completed, and verified, and served.
        v_should_count :=
          v_status = 'completed'
          and v_attendance = 'served'
          and v_verification in ('live_timer', 'qr_scan', 'member_verified');

        if (v_result = 'counted') <> v_should_count then
          raise exception
            'points_status(%, %, %) is % — counted should be %.',
            v_status, v_attendance, v_verification, v_result, v_should_count;
        end if;

        -- Somebody said they were not there.
        v_should_refuse :=
          v_status in ('no_show', 'withdrawn')
          or v_attendance in ('absent', 'excused');

        if (v_result = 'not_served') <> v_should_refuse then
          raise exception
            'points_status(%, %, %) is % — not_served should be %.',
            v_status, v_attendance, v_verification, v_result, v_should_refuse;
        end if;

        -- Everything else is a queue, never a fourth kind of verdict.
        if not v_should_count and not v_should_refuse
          and v_result not in (
            'awaiting_completion', 'awaiting_verification', 'awaiting_confirmation')
        then
          raise exception
            'points_status(%, %, %) is %, which is neither counted, refused, nor waiting.',
            v_status, v_attendance, v_verification, v_result;
        end if;

        -- Whatever it says, it says something a devotee can read.
        if public.seva_points_note(v_result) is null then
          raise exception 'points_status % has no sentence to show a devotee.', v_result;
        end if;
      end loop;
    end loop;
  end loop;

  if v_seen <> 80 then
    raise exception 'The cross product was % combinations rather than eighty.', v_seen;
  end if;
end;
$$;

-- The order of the branches: an act blocked on two things reports the earliest
-- one somebody can act on, not whichever branch happened to be typed first.
do $$
begin
  if public.seva_points_status('assigned', null, 'self_report') <> 'awaiting_completion' then
    raise exception 'An unclosed, unverified, unmarked act does not ask to be closed out first.';
  end if;
  if public.seva_points_status('completed', null, 'self_report') <> 'awaiting_verification' then
    raise exception 'A closed but unverified act does not ask to be verified.';
  end if;
  if public.seva_points_status('completed', null, 'member_verified') <> 'awaiting_confirmation' then
    raise exception 'A closed and verified act with no attendance mark does not ask to be confirmed.';
  end if;
  if public.seva_points_status('withdrawn', 'served', 'qr_scan') <> 'not_served' then
    raise exception 'A withdrawal marked served and scanned is not refused.';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 2. The congregation.
-- ---------------------------------------------------------------------------

do $$
declare
  v_who text;
  v_i integer := 0;
begin
  foreach v_who in array array[
    'poster', 'president', 'alldone', 'unmarked', 'absent', 'excused',
    'selfsaid', 'unclosed', 'noshow', 'weekly', 'timer', 'orphan', 'other',
    'capped', 'soloist'
  ] loop
    v_i := v_i + 1;
    insert into auth.users (id, email, raw_user_meta_data)
    values (
      ('57000000-0000-0000-0000-0000000000' || lpad(v_i::text, 2, '0'))::uuid,
      'pe-' || v_who || '@example.test',
      jsonb_build_object('name', initcap(v_who) || ' Das')
    );
  end loop;
end;
$$;

update public.users
set role_id = (select roles.id from public.roles where roles.name = 'president')
where users.email = 'pe-president@example.test';

-- Ordinary table rather than a temporary one, so reading it under the
-- authenticated role needs no assumptions about the temp schema. The whole
-- script is rolled back, so it never outlives the transaction.
create table public.seva_pe_ids (key text primary key, id uuid not null);
grant select on public.seva_pe_ids to authenticated;

insert into public.seva_pe_ids (key, id)
select split_part(split_part(users.email, '@', 1), 'pe-', 2), users.id
from public.users
where users.email like 'pe-%@example.test';

create table public.seva_pe_acts (key text primary key, assignment_id uuid not null);
grant select on public.seva_pe_acts to authenticated;

-- ---------------------------------------------------------------------------
-- 3. The facts.
--
--    Everything on today's Chicago date at midnight, so the seva has always
--    already started whatever hour the harness runs at, and so the week, the
--    month and the year windows all contain it. One act sits on the first of
--    January so the year window has something the week does not — and in the
--    first days of a January that is the same day, which the expectations below
--    account for rather than pretend cannot happen.
-- ---------------------------------------------------------------------------

do $$
declare
  v_type uuid;
  v_today date := public.seva_mala_today();
  v_jan1 date := date_trunc('year', public.seva_mala_today()::timestamp)::date;
  v_case record;
  v_instance uuid;
  v_assignment uuid;
begin
  select service_types.id into v_type
  from public.service_types where service_types.name = 'Pot Washing';

  for v_case in
    select * from (values
      -- key,        who,        day,      type,    minutes, status,      attendance, verification,  posted
      ('a1',         'alldone',  'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('a2',         'alldone',  'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('a3',         'alldone',  'today',  'custom', 60, 'completed', 'served', 'member_verified', 'poster'),
      ('a4',         'alldone',  'jan1',   'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('a5',         'alldone',  'today',  'pot',   120, 'completed', null,     'member_verified', 'poster'),
      ('unmarked',   'unmarked', 'today',  'pot',   120, 'completed', null,     'member_verified', 'poster'),
      ('absent',     'absent',   'today',  'pot',   120, 'completed', 'absent', 'member_verified', 'poster'),
      ('excused',    'excused',  'today',  'pot',   120, 'completed', 'excused','member_verified', 'poster'),
      ('selfsaid',   'selfsaid', 'today',  'pot',   120, 'completed', 'served', 'self_report',     'poster'),
      ('unclosed',   'unclosed', 'today',  'pot',   120, 'confirmed', 'served', 'member_verified', 'poster'),
      ('noshow',     'noshow',   'today',  'pot',   120, 'no_show',   'served', 'member_verified', 'poster'),
      ('orphan',     'orphan',   'today',  'pot',   120, 'completed', null,     'member_verified', null),
      ('timer',      'timer',    'today',  'pot',   120, 'completed', 'served', 'live_timer',      'poster'),
      -- Ten hours in one day against an eight-hour cap, and a waiting act
      -- beside them that must not be allowed to eat any of it.
      ('c1',         'capped',   'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('c2',         'capped',   'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('c3',         'capped',   'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('c4',         'capped',   'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('c5',         'capped',   'today',  'pot',   120, 'completed', 'served', 'member_verified', 'poster'),
      ('c6',         'capped',   'today',  'pot',   120, 'completed', null,     'member_verified', 'poster'),
      ('solo',       'soloist',  'today',  'pot',   120, 'completed', null,     'self_report',     'soloist')
    ) as spec(key, who, day, kind, minutes, status, attendance, verification, posted)
  loop
    insert into public.service_instances (
      service_type_id, custom_name, date, start_time, duration_minutes,
      slots_needed, participation_mode, posted_by, status
    ) values (
      case when v_case.kind = 'pot' then v_type end,
      case when v_case.kind = 'custom' then 'Deity Garland Making' end,
      case when v_case.day = 'today' then v_today else v_jan1 end,
      time '00:00',
      v_case.minutes,
      1,
      'open',
      (select ids.id from public.seva_pe_ids ids where ids.key = v_case.posted),
      'completed'
    ) returning id into v_instance;

    insert into public.service_assignments (
      service_instance_id, devotee_id, assignment_method, status,
      verification, attendance, completed_at
    ) values (
      v_instance,
      (select ids.id from public.seva_pe_ids ids where ids.key = v_case.who),
      'self_joined', v_case.status, v_case.verification, v_case.attendance,
      case when v_case.status = 'completed'
        then (case when v_case.day = 'today' then v_today else v_jan1 end
              + time '02:00') at time zone 'America/Chicago'
      end
    ) returning id into v_assignment;

    insert into public.seva_pe_acts (key, assignment_id) values (v_case.key, v_assignment);

    -- Say again that the occurrence is finished.
    --
    -- The insert above already asked for 'completed', but adding an assignment
    -- that holds no live place — a no_show, a withdrawal — makes the seva
    -- recompute its own status back to 'open', because a place has come free.
    -- That is right for a seva still ahead of us and wrong for these fixtures,
    -- which describe seva that is over.
    --
    -- It matters since 202608310083: an act counts once its seva has ENDED or
    -- is marked completed, and these run 00:00-02:00 today. Left as 'open',
    -- the whole fixture vanished from the board between midnight and two in
    -- the morning — which is exactly when this file first failed.
    update public.service_instances
    set status = 'completed'
    where id = v_instance;

    -- The timer nobody switched off.
    if v_case.key = 'timer' then
      insert into public.service_qr_sessions (
        devotee_id, service_type_id, started_at, planned_end_at, completed_at,
        status, service_instance_id, started_via, auto_completed
      ) values (
        (select ids.id from public.seva_pe_ids ids where ids.key = 'timer'),
        v_type,
        (v_today + time '00:00') at time zone 'America/Chicago',
        (v_today + time '02:00') at time zone 'America/Chicago',
        (v_today + time '02:00') at time zone 'America/Chicago',
        'completed', v_instance, 'service_list', true
      );
    end if;
  end loop;
end;
$$;

-- Two gifts, so the devotee's own giving has a window to be wrong about.
insert into public.donations (
  donor_id, donor_name, amount_cents, kind, external_payment_id, received_at
)
select ids.id, 'Alldone Das', 7500, 'one_time', 'pe-alldone-today',
       (public.seva_mala_today() + time '01:00') at time zone 'America/Chicago'
from public.seva_pe_ids ids where ids.key = 'alldone';

insert into public.donations (
  donor_id, donor_name, amount_cents, kind, external_payment_id, received_at
)
select ids.id, 'Alldone Das', 2500, 'one_time', 'pe-alldone-jan',
       (date_trunc('year', public.seva_mala_today()::timestamp)::date + time '01:00')
         at time zone 'America/Chicago'
from public.seva_pe_ids ids where ids.key = 'alldone';

-- ---------------------------------------------------------------------------
-- 4. Weekly seva, through the real generator and the real RPCs.
--
--    Not a hand-written row with template_id set. A real service_templates row,
--    a real standing assignee, public.generate_service_instances, and then the
--    three authorised acts the temple named — closed, verified, confirmed —
--    each through the RPC a President would actually press.
--
--    Recurring instances carry posted_by null, so every one of those three is
--    the President's here. That is 202608040027's authority, not this file's
--    choice, and it is why the President appears in all three calls.
--
--    HOW LONG THE SEVA IS, AND WHY IT IS NOT ALWAYS TWO HOURS. 202608040070
--    moved the completion bar from a seva's start to its end, and the President
--    closes this occurrence out below, so its whole length has to be behind us
--    before the button will work. Two fixed hours from midnight meant this file
--    passed after 02:00 Chicago and failed before it.
--
--    The occurrence cannot be moved off today to escape that. The generator
--    only ever writes today forward, and section 8 reads this act back out of
--    the devotee's WEEK — a seva moved to yesterday would leave that window
--    entirely every time the suite ran on the first day of a Chicago week. So
--    the day stays and the length gives: the seva starts at midnight and runs
--    for as much of the day as has actually elapsed, capped at the two hours it
--    has always been. Any run after 02:00 is byte for byte the old fixture; a
--    run at 00:05 gets a five-minute seva that genuinely finished.
--
--    Every assertion about this act reads its length back out of seva_pe_facts
--    rather than repeating a literal, so the shorter seva is asserted exactly
--    as hard as the two-hour one and no expectation can quietly drift off it.
-- ---------------------------------------------------------------------------

create table public.seva_pe_facts (key text primary key, minutes integer not null);
grant select on public.seva_pe_facts to authenticated;

do $$
declare
  v_type uuid;
  v_today date := public.seva_mala_today();
  v_president uuid;
  v_template uuid;
  -- now() is the transaction's, so this is the same instant the completion bar
  -- is measured against further down. Whole minutes, and never zero, because
  -- service_templates_duration_minutes_check wants at least one.
  v_elapsed_minutes integer := floor(
    extract(epoch from (now() at time zone 'America/Chicago')::time) / 60.0)::integer;
  v_minutes integer := greatest(1, least(120, v_elapsed_minutes));
begin
  select service_types.id into v_type
  from public.service_types where service_types.name = 'Pot Washing';
  select ids.id into v_president from public.seva_pe_ids ids where ids.key = 'president';

  insert into public.seva_pe_facts (key, minutes) values ('weekly', v_minutes);

  insert into public.service_templates (
    service_type_id, day_of_week, days_of_week, start_time, duration_minutes,
    slots_needed, participation_mode, start_date, created_by, active
  ) values (
    v_type, extract(dow from v_today)::integer, array[0, 1, 2, 3, 4, 5, 6],
    time '00:00', v_minutes, 1, 'open', v_today, v_president, true
  ) returning id into v_template;

  insert into public.service_template_assignees (
    service_template_id, devotee_id, assigned_by, status, days_of_week
  )
  select v_template, ids.id, v_president, 'active', array[0, 1, 2, 3, 4, 5, 6]
  from public.seva_pe_ids ids where ids.key = 'weekly';

  perform public.generate_service_instances(1);
end;
$$;

do $$
declare
  v_assignment uuid;
  v_instance uuid;
  v_status text;
begin
  select assignments.id, instances.id into v_assignment, v_instance
  from public.service_assignments assignments
  join public.service_instances instances
    on instances.id = assignments.service_instance_id
  where assignments.devotee_id
        = (select ids.id from public.seva_pe_ids ids where ids.key = 'weekly')
    and instances.template_id is not null
    and instances.date = public.seva_mala_today();

  if v_assignment is null then
    raise exception 'The generator did not place the weekly devotee on today''s instance.';
  end if;

  -- As generated: confirmed, self-reported, unconfirmed. Which is to say the
  -- state every recurring assignment in the temple is in right now.
  select public.seva_points_status(
           assignments.status, assignments.attendance, assignments.verification)
  into v_status
  from public.service_assignments assignments where assignments.id = v_assignment;
  if v_status <> 'awaiting_completion' then
    raise exception 'A freshly generated weekly assignment reads % rather than awaiting_completion.',
      v_status;
  end if;

  insert into public.seva_pe_acts (key, assignment_id) values ('weekly', v_assignment);
end;
$$;

set local role authenticated;
select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'president'), true);

do $$
declare
  v_assignment uuid;
  v_instance uuid;
  v_opens_at timestamptz;
begin
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'weekly';
  select assignments.service_instance_id into v_instance
  from public.service_assignments assignments where assignments.id = v_assignment;

  -- The clock, said out loud before the button is pressed. If this ever fires,
  -- the length above and the hour the harness runs at have come apart, and the
  -- file must say so rather than fail three sections later on a points status.
  select public.seva_completion_opens_at(
           instances.date, instances.start_time, instances.duration_minutes)
    into v_opens_at
  from public.service_instances instances where instances.id = v_instance;
  if v_opens_at > now() then
    raise exception
      'The weekly occurrence is not over until %, so the President cannot close it out.',
      v_opens_at;
  end if;

  perform public.complete_service_instance(v_instance);
  perform public.verify_seva_assignment(v_assignment);
  -- No attendance mark: 202608040059 counts a weekly act on completion alone,
  -- and 202608310098 refuses the mark outright — a rota runs by itself, and a
  -- devotee who cannot make their day asks for coverage.
end;
$$;

reset role;
select set_config('request.jwt.claim.sub', '', true);

select public.recompute_seva_mala() as periods_computed;

-- ---------------------------------------------------------------------------
-- 5. Act by act: what earned, and what earned nothing at all.
--
--    Asserted against seva_mala_acts rather than against a score, because a
--    score is a sum and a sum can hide a zero.
-- ---------------------------------------------------------------------------

do $$
declare
  v_case record;
  v_status text;
  v_quality numeric;
  v_weighted numeric;
  v_raw numeric;
  -- The weekly seva's own length, whatever the hour made it. Quality 1.0 and a
  -- scarcity weight of 1.0 mean a counted act is worth its minutes exactly, so
  -- weighted and served are the same number and both are this one.
  v_weekly numeric := (select facts.minutes from public.seva_pe_facts facts
                       where facts.key = 'weekly');
begin
  for v_case in
    select * from (values
      -- key,       points_status,           quality, weighted, served
      ('a1',       'counted',               1.0, 120.0, 120.0),
      ('a3',       'counted',               1.0,  60.0,  60.0),
      ('a5',       'awaiting_confirmation', 0.0,   0.0, 120.0),
      ('unmarked', 'awaiting_confirmation', 0.0,   0.0, 120.0),
      ('absent',   'not_served',            0.0,   0.0, 120.0),
      ('excused',  'not_served',            0.0,   0.0, 120.0),
      ('selfsaid', 'awaiting_verification', 0.0,   0.0, 120.0),
      ('unclosed', 'awaiting_completion',   0.0,   0.0, 120.0),
      ('noshow',   'not_served',            0.0,   0.0, 120.0),
      ('orphan',   'awaiting_confirmation', 0.0,   0.0, 120.0),
      ('timer',    'counted',               0.7,  84.0, 120.0),
      ('weekly',   'counted',               1.0, v_weekly, v_weekly),
      -- 480 credited minutes shared over five acts, so each is worth 0.8 of
      -- itself. If the waiting act spent cap, this would be 80 rather than 96.
      ('c1',       'counted',               1.0,  96.0, 120.0),
      ('c6',       'awaiting_confirmation', 0.0,   0.0, 120.0)
    ) as spec(key, points_status, quality, weighted, served)
  loop
    select acts.points_status, acts.quality, acts.weighted_minutes, acts.raw_minutes
    into v_status, v_quality, v_weighted, v_raw
    from public.seva_mala_acts() acts
    join public.seva_pe_acts ids on ids.assignment_id = acts.assignment_id
    where ids.key = v_case.key;

    if v_status is distinct from v_case.points_status then
      raise exception '% reads % rather than %.', v_case.key, v_status, v_case.points_status;
    end if;
    if v_quality is distinct from v_case.quality then
      raise exception '% earns quality % rather than %.', v_case.key, v_quality, v_case.quality;
    end if;
    if v_weighted is distinct from v_case.weighted then
      raise exception '% is worth % weighted minutes rather than %.',
        v_case.key, v_weighted, v_case.weighted;
    end if;

    -- The hours survive whatever the points did. This is the difference between
    -- "we are still confirming it" and "it never happened".
    if v_raw is distinct from v_case.served then
      raise exception '% recorded % minutes served rather than %.',
        v_case.key, v_raw, v_case.served;
    end if;
  end loop;
end;
$$;

-- And at the level the scoring actually reads: the devotees whose seva is
-- waiting have no score row at all, while the three who satisfied all three
-- conditions do.
do $$
declare
  v_who text;
  v_rows integer;
  v_lifetime uuid;
  v_credited numeric;
begin
  select periods.id into v_lifetime
  from public.seva_mala_periods periods where periods.period_kind = 'lifetime';

  foreach v_who in array array['unmarked', 'absent', 'excused', 'selfsaid', 'unclosed',
                               'noshow', 'orphan'] loop
    select count(*) into v_rows
    from public.period_scores scores
    join public.seva_pe_ids ids on ids.id = scores.devotee_id
    where scores.period_id = v_lifetime and ids.key = v_who;
    if v_rows <> 0 then
      raise exception '% was scored despite earning no points.', v_who;
    end if;
  end loop;

  foreach v_who in array array['alldone', 'timer', 'weekly', 'capped'] loop
    select scores.credited_minutes into v_credited
    from public.period_scores scores
    join public.seva_pe_ids ids on ids.id = scores.devotee_id
    where scores.period_id = v_lifetime and ids.key = v_who;
    if v_credited is null or v_credited <= 0 then
      raise exception '% satisfied all three conditions and was credited %.', v_who, v_credited;
    end if;
  end loop;

  -- Alldone: three counted acts today plus one in January, and nothing for the
  -- act still waiting. 120 + 120 + 60 + 120.
  select scores.credited_minutes into v_credited
  from public.period_scores scores
  join public.seva_pe_ids ids on ids.id = scores.devotee_id
  where scores.period_id = v_lifetime and ids.key = 'alldone';
  if v_credited <> 420 then
    raise exception 'Alldone was credited % minutes rather than 420.', v_credited;
  end if;

  -- The cap is a claim about the physical day, and a waiting act is not part
  -- of it. Ten hours served, eight credited — not eight shared over twelve.
  select scores.credited_minutes into v_credited
  from public.period_scores scores
  join public.seva_pe_ids ids on ids.id = scores.devotee_id
  where scores.period_id = v_lifetime and ids.key = 'capped';
  if v_credited <> 480 then
    raise exception
      'Ten hours served against an eight-hour cap credited % minutes rather than 480.',
      v_credited;
  end if;

  -- The scarcity weight is 1.0 with a single service type, so every weighted
  -- figure above is the quality multiplier and nothing else.
  if exists (select 1 from public.seva_type_weights where weight <> 1.0) then
    raise exception 'A single service type produced a scarcity weight other than 1.0.';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. What the devotee sees.
--
--    The whole reason this file is longer than the rule it verifies. A devotee
--    whose every act is waiting must get an answer, and the answer must say
--    what is waiting and on whom.
-- ---------------------------------------------------------------------------

set local role authenticated;
select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'unmarked'), true);

do $$
declare
  v_rows integer;
  v_score numeric;
  v_pending_acts integer;
  v_pending_minutes integer;
  v_seva_acts integer;
  v_status text;
  v_note text;
  v_weekday text;
  v_hours numeric;
  v_recurring boolean;
begin
  select count(*) into v_rows from public.my_seva_mala('week');
  if v_rows <> 1 then
    raise exception
      'A devotee with nothing but a waiting seva got % rows from my_seva_mala.', v_rows;
  end if;

  select mine.score, mine.seva_acts, mine.pending_acts, mine.pending_minutes
  into v_score, v_seva_acts, v_pending_acts, v_pending_minutes
  from public.my_seva_mala('week') mine;

  if v_score <> 0 then
    raise exception 'An unconfirmed seva scored %.', v_score;
  end if;
  if v_seva_acts <> 0 then
    raise exception 'An unconfirmed seva counted as % acts.', v_seva_acts;
  end if;
  if v_pending_acts <> 1 then
    raise exception 'The devotee was told % acts are waiting rather than one.', v_pending_acts;
  end if;
  if v_pending_minutes <> 120 then
    raise exception 'The devotee was told % minutes are waiting rather than 120.',
      v_pending_minutes;
  end if;

  -- Act by act, with the reason in words.
  select count(*) into v_rows from public.my_seva_acts();
  if v_rows <> 1 then
    raise exception 'my_seva_acts returned % acts to a devotee who served one.', v_rows;
  end if;

  select acts.points_status, acts.points_note, acts.weekday, acts.hours, acts.is_recurring
  into v_status, v_note, v_weekday, v_hours, v_recurring
  from public.my_seva_acts() acts;

  if v_status <> 'awaiting_confirmation' then
    raise exception 'The devotee is told their act is %.', v_status;
  end if;
  if v_note is null or position('confirm' in lower(v_note)) = 0 then
    raise exception 'The sentence shown to the devotee does not mention confirmation: %.', v_note;
  end if;
  if v_hours <> 2.00 then
    raise exception 'A two-hour seva is shown as % hours.', v_hours;
  end if;
  if v_recurring then
    raise exception 'A one-off seva is shown as weekly seva.';
  end if;
  if v_weekday <> trim(to_char(public.seva_mala_today(), 'FMDay')) then
    raise exception 'The act is dated % rather than today''s weekday.', v_weekday;
  end if;

  -- And the hours are not withheld along with the points.
  select profile.pending_hours, profile.counted_hours
  into v_hours, v_score
  from public.my_seva_profile() profile where profile.window_kind = 'week';
  if v_hours <> 2.00 then
    raise exception 'The waiting seva shows % hours rather than two.', v_hours;
  end if;
  if v_score <> 0.00 then
    raise exception 'A waiting seva was counted as % hours of points.', v_score;
  end if;
end;
$$;

-- Every kind of waiting counts as waiting. A devotee blocked on completion and
-- a devotee blocked on verification are as much in the queue as one blocked on
-- the attendance mark, and a pending count that quietly omits either is worse
-- than no pending count at all — it tells a devotee their seva simply vanished.
do $$
declare
  v_who text;
  v_expected text;
  v_acts integer;
  v_minutes integer;
  v_status text;
begin
  foreach v_who in array array['unclosed', 'selfsaid'] loop
    v_expected := case v_who
      when 'unclosed' then 'awaiting_completion'
      else 'awaiting_verification'
    end;
    perform set_config('request.jwt.claim.sub',
      (select ids.id::text from public.seva_pe_ids ids where ids.key = v_who), true);

    select mine.pending_acts, mine.pending_minutes into v_acts, v_minutes
    from public.my_seva_mala('week') mine;
    if v_acts <> 1 or v_minutes <> 120 then
      raise exception '% is told % acts and % minutes are waiting rather than one and 120.',
        v_who, v_acts, v_minutes;
    end if;

    select acts.points_status into v_status from public.my_seva_acts() acts;
    if v_status <> v_expected then
      raise exception '% is told their act is % rather than %.', v_who, v_status, v_expected;
    end if;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- 7. The windows, the breakdown, and the giving beside them.
-- ---------------------------------------------------------------------------

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'alldone'), true);

do $$
declare
  v_today date := public.seva_mala_today();
  v_jan1 date := date_trunc('year', public.seva_mala_today()::timestamp)::date;
  -- Written out rather than read from seva_mala_windows, so the windows are
  -- checked against arithmetic and not against themselves.
  v_week_start date := public.seva_mala_today()
                       - (extract(isodow from public.seva_mala_today())::integer - 1);
  v_month_start date := date_trunc('month', public.seva_mala_today()::timestamp)::date;
  v_in_week integer := 0;
  v_in_month integer := 0;
  v_row record;
  v_rows integer;
begin
  if v_jan1 between v_week_start and v_week_start + 6 then v_in_week := 1; end if;
  if v_jan1 >= v_month_start then v_in_month := 1; end if;

  -- Three windows, and the profile agrees with the arithmetic above.
  select count(*) into v_rows from public.my_seva_profile();
  if v_rows <> 3 then
    raise exception 'The profile returned % windows rather than week, month and year.', v_rows;
  end if;

  select * into v_row from public.my_seva_profile() profile where profile.window_kind = 'week';
  if v_row.window_start <> v_week_start or v_row.window_end <> v_week_start + 6 then
    raise exception 'The week window is % to %.', v_row.window_start, v_row.window_end;
  end if;
  if v_row.acts <> 4 + v_in_week then
    raise exception 'The week holds % acts rather than %.', v_row.acts, 4 + v_in_week;
  end if;
  if v_row.counted_acts <> 3 + v_in_week then
    raise exception 'The week counted % acts rather than %.',
      v_row.counted_acts, 3 + v_in_week;
  end if;
  if v_row.counted_hours <> 5.00 + v_in_week * 2 then
    raise exception 'The week counted % hours rather than %.',
      v_row.counted_hours, 5.00 + v_in_week * 2;
  end if;
  if v_row.pending_acts <> 1 or v_row.pending_hours <> 2.00 then
    raise exception 'The week has % waiting acts and % waiting hours.',
      v_row.pending_acts, v_row.pending_hours;
  end if;
  if v_row.not_served_acts <> 0 then
    raise exception 'The week recorded % acts as not served.', v_row.not_served_acts;
  end if;
  if v_row.hours <> v_row.counted_hours + v_row.pending_hours + v_row.not_served_hours then
    raise exception 'Counted, waiting and not served do not sum to the total hours.';
  end if;

  -- Giving, in the devotee's own view, in the same window.
  if v_row.giving_cents <> 7500 + v_in_week * 2500 then
    raise exception 'The week shows % cents given rather than %.',
      v_row.giving_cents, 7500 + v_in_week * 2500;
  end if;
  if v_row.gifts <> 1 + v_in_week then
    raise exception 'The week shows % gifts rather than %.', v_row.gifts, 1 + v_in_week;
  end if;

  select * into v_row from public.my_seva_profile() profile where profile.window_kind = 'month';
  if v_row.window_start <> v_month_start then
    raise exception 'The month window starts on %.', v_row.window_start;
  end if;
  if v_row.counted_acts <> 3 + v_in_month then
    raise exception 'The month counted % acts rather than %.',
      v_row.counted_acts, 3 + v_in_month;
  end if;
  if v_row.giving_cents <> 7500 + v_in_month * 2500 then
    raise exception 'The month shows % cents given.', v_row.giving_cents;
  end if;

  -- The year holds everything, whatever day of the year it is.
  select * into v_row from public.my_seva_profile() profile where profile.window_kind = 'year';
  if v_row.window_start <> v_jan1 then
    raise exception 'The year window starts on % rather than %.', v_row.window_start, v_jan1;
  end if;
  if v_row.acts <> 5 or v_row.counted_acts <> 4 or v_row.pending_acts <> 1 then
    raise exception 'The year holds % acts, % counted, % waiting.',
      v_row.acts, v_row.counted_acts, v_row.pending_acts;
  end if;
  if v_row.counted_hours <> 7.00 or v_row.hours <> 9.00 then
    raise exception 'The year counted % of % hours.', v_row.counted_hours, v_row.hours;
  end if;
  if v_row.giving_cents <> 10000 or v_row.gifts <> 2 then
    raise exception 'The year shows % cents over % gifts.', v_row.giving_cents, v_row.gifts;
  end if;
end;
$$;

-- Per kind of seva, per window.
do $$
declare
  v_jan1 date := date_trunc('year', public.seva_mala_today()::timestamp)::date;
  v_week_start date := public.seva_mala_today()
                       - (extract(isodow from public.seva_mala_today())::integer - 1);
  v_in_week integer := 0;
  v_row record;
  v_rows integer;
begin
  if v_jan1 between v_week_start and v_week_start + 6 then v_in_week := 1; end if;

  -- Two kinds of seva in the week, and the custom-named one keeps its own row
  -- rather than collapsing into an anonymous bucket with no service type.
  select count(*) into v_rows
  from public.my_seva_breakdown() breakdown where breakdown.window_kind = 'week';
  if v_rows <> 2 then
    raise exception 'The week breaks down into % kinds of seva rather than two.', v_rows;
  end if;

  select * into v_row from public.my_seva_breakdown() breakdown
  where breakdown.window_kind = 'week' and breakdown.seva_name = 'Pot Washing';
  if v_row.acts <> 3 + v_in_week or v_row.hours <> 6.00 + v_in_week * 2 then
    raise exception 'Pot Washing this week is % acts over % hours.', v_row.acts, v_row.hours;
  end if;
  if v_row.counted_acts <> 2 + v_in_week or v_row.counted_hours <> 4.00 + v_in_week * 2 then
    raise exception 'Pot Washing counted % acts over % hours this week.',
      v_row.counted_acts, v_row.counted_hours;
  end if;
  if v_row.pending_acts <> 1 or v_row.pending_hours <> 2.00 then
    raise exception 'Pot Washing has % acts waiting this week.', v_row.pending_acts;
  end if;
  if v_row.service_type_id is null then
    raise exception 'A seva with a service type lost it in the breakdown.';
  end if;

  select * into v_row from public.my_seva_breakdown() breakdown
  where breakdown.window_kind = 'week' and breakdown.seva_name = 'Deity Garland Making';
  if v_row.acts <> 1 or v_row.hours <> 1.00 or v_row.counted_hours <> 1.00 then
    raise exception 'The custom-named seva is % acts over % hours.', v_row.acts, v_row.hours;
  end if;
  if v_row.service_type_id is not null then
    raise exception 'A custom-named seva acquired a service type.';
  end if;

  -- The year holds the January act under the same kind.
  select * into v_row from public.my_seva_breakdown() breakdown
  where breakdown.window_kind = 'year' and breakdown.seva_name = 'Pot Washing';
  if v_row.acts <> 4 or v_row.hours <> 8.00 or v_row.counted_hours <> 6.00 then
    raise exception 'Pot Washing this year is % acts over % hours, % counted.',
      v_row.acts, v_row.hours, v_row.counted_hours;
  end if;
end;
$$;

-- The devotee's own giving also reaches my_seva_mala, unchanged by any of this.
do $$
declare
  v_cents bigint;
  v_gifts integer;
begin
  select mine.giving_cents, mine.gifts into v_cents, v_gifts
  from public.my_seva_mala('lifetime') mine;
  if v_cents <> 10000 or v_gifts <> 2 then
    raise exception 'my_seva_mala shows % cents over % gifts for a lifetime.', v_cents, v_gifts;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 8. Weekly seva, in the devotee's own profile.
--
--    Which seva, which day, how many hours — and that it counted like anything
--    else once the three conditions were met.
-- ---------------------------------------------------------------------------

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'weekly'), true);

do $$
declare
  v_row record;
  v_act record;
  -- The same length section 4 gave the occurrence, in the hours these three
  -- readings are expressed in. round(minutes / 60, 2) is what my_seva_profile,
  -- my_seva_acts and my_seva_breakdown each do to it, so this is their
  -- arithmetic and not a rounding of this file's own.
  v_weekly_hours numeric := (
    select round(facts.minutes / 60.0, 2) from public.seva_pe_facts facts
    where facts.key = 'weekly');
begin
  select * into v_row from public.my_seva_profile() profile where profile.window_kind = 'week';
  if v_row.recurring_acts <> 1 or v_row.recurring_hours <> v_weekly_hours then
    raise exception 'The weekly devotee''s week shows % recurring acts over % hours rather than %.',
      v_row.recurring_acts, v_row.recurring_hours, v_weekly_hours;
  end if;
  if v_row.counted_acts <> 1 or v_row.counted_hours <> v_weekly_hours then
    raise exception 'Weekly seva that met all three conditions counted % acts over % hours.',
      v_row.counted_acts, v_row.counted_hours;
  end if;
  if v_row.pending_acts <> 0 then
    raise exception 'Confirmed weekly seva is still waiting on %.', v_row.pending_acts;
  end if;

  -- Which seva, which day, how many hours.
  select * into v_act from public.my_seva_acts() acts;
  if not v_act.is_recurring then
    raise exception 'Weekly seva is not shown as weekly.';
  end if;
  if v_act.seva_name <> 'Pot Washing' then
    raise exception 'The weekly seva is named %.', v_act.seva_name;
  end if;
  if v_act.weekday <> trim(to_char(public.seva_mala_today(), 'FMDay')) then
    raise exception 'The weekly seva fell on % rather than today.', v_act.weekday;
  end if;
  if v_act.hours <> v_weekly_hours then
    raise exception 'The weekly seva is % hours rather than %.', v_act.hours, v_weekly_hours;
  end if;
  if v_act.points_status <> 'counted' then
    raise exception 'Weekly seva reads % after all three conditions were met.',
      v_act.points_status;
  end if;

  -- And the breakdown carries it under its own kind.
  select * into v_row from public.my_seva_breakdown() breakdown
  where breakdown.window_kind = 'week' and breakdown.seva_name = 'Pot Washing';
  if v_row.recurring_acts <> 1 or v_row.counted_hours <> v_weekly_hours then
    raise exception
      'Weekly Pot Washing breaks down to % recurring acts, % counted hours rather than %.',
      v_row.recurring_acts, v_row.counted_hours, v_weekly_hours;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 9. Whose queue it is.
-- ---------------------------------------------------------------------------

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'other'), true);

do $$
declare
  v_rows integer;
begin
  select count(*) into v_rows from public.list_seva_awaiting_confirmation();
  if v_rows <> 0 then
    raise exception
      'A devotee who posted nothing and holds nothing sees % waiting sevas.', v_rows;
  end if;

  -- And reads nothing about anybody else through their own profile.
  select count(*) into v_rows from public.my_seva_acts();
  if v_rows <> 0 then
    raise exception 'A devotee with no seva was shown % acts.', v_rows;
  end if;
  select profile.giving_cents into v_rows
  from public.my_seva_profile() profile where profile.window_kind = 'year';
  if v_rows <> 0 then
    raise exception 'A devotee who gave nothing was shown % cents.', v_rows;
  end if;
end;
$$;

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'poster'), true);

do $$
declare
  v_rows integer;
  v_orphan integer;
begin
  -- a5, c6, unmarked, selfsaid and unclosed are waiting on seva this devotee
  -- posted. The ones marked absent, excused or a no-show are not waiting on
  -- anybody and must not clutter the queue.
  select count(*) into v_rows from public.list_seva_awaiting_confirmation();
  if v_rows <> 5 then
    raise exception 'The poster sees % waiting sevas rather than five.', v_rows;
  end if;

  select count(*) into v_orphan
  from public.list_seva_awaiting_confirmation() waiting
  join public.seva_pe_ids ids on ids.id = waiting.devotee_id
  where ids.key = 'orphan';
  if v_orphan <> 0 then
    raise exception 'The poster sees a waiting seva they did not post.';
  end if;
end;
$$;

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'president'), true);

do $$
declare
  v_rows integer;
  v_note text;
begin
  select count(*) into v_rows from public.list_seva_awaiting_confirmation();
  if v_rows <> 7 then
    raise exception 'The President sees % waiting sevas rather than seven.', v_rows;
  end if;

  select waiting.points_note into v_note
  from public.list_seva_awaiting_confirmation() waiting
  join public.seva_pe_ids ids on ids.id = waiting.devotee_id
  where ids.key = 'orphan';
  if v_note is null or position('confirm' in lower(v_note)) = 0 then
    raise exception 'The President is not told what the orphaned seva is waiting for.';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 10. Who may say it happened.
-- ---------------------------------------------------------------------------

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'selfsaid'), true);

do $$
declare
  v_assignment uuid;
begin
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'selfsaid';

  begin
    perform public.verify_seva_assignment(v_assignment);
    raise exception 'A devotee verified their own seva.';
  exception when others then
    if position('other than you' in sqlerrm) = 0 then raise; end if;
  end;

  begin
    perform public.record_seva_attendance(v_assignment, 'served');
    raise exception 'A devotee recorded their own attendance on somebody else''s seva.';
  exception when others then
    if position('posted this seva' in sqlerrm) = 0 then raise; end if;
  end;
end;
$$;

select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'other'), true);

do $$
declare
  v_assignment uuid;
begin
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'selfsaid';

  begin
    perform public.verify_seva_assignment(v_assignment);
    raise exception 'An unrelated devotee verified somebody else''s seva.';
  exception when others then
    if position('posted this seva' in sqlerrm) = 0 then raise; end if;
  end;
end;
$$;

-- The case the live timer creates on every act it writes: the devotee posted
-- the seva and served it. They hold the authority over it — they may close it
-- out and they may mark their own attendance — and they are still not somebody
-- other than themselves. Without this the whole verification requirement is one
-- devotee's two taps.
select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'soloist'), true);

do $$
declare
  v_assignment uuid;
  v_status text;
begin
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'solo';

  begin
    perform public.verify_seva_assignment(v_assignment);
    raise exception 'The devotee who posted their own seva verified themselves.';
  exception when others then
    if position('other than you' in sqlerrm) = 0 then raise; end if;
  end;

  -- And so it stays waiting, and they are told exactly what for.
  select acts.points_status into v_status from public.my_seva_acts() acts;
  if v_status <> 'awaiting_verification' then
    raise exception 'A self-posted, self-served seva reads %.', v_status;
  end if;
end;
$$;

-- The poster may, and the act that was waiting on exactly that becomes points.
select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'poster'), true);

do $$
declare
  v_assignment uuid;
  v_verification text;
begin
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'selfsaid';

  perform public.verify_seva_assignment(v_assignment);

  select assignments.verification into v_verification
  from public.service_assignments assignments where assignments.id = v_assignment;
  if v_verification <> 'member_verified' then
    raise exception 'The poster verified the seva and it reads %.', v_verification;
  end if;

  -- A live timer's account outranks a person's and is never replaced by one.
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'timer';
  perform public.verify_seva_assignment(v_assignment);
  select assignments.verification into v_verification
  from public.service_assignments assignments where assignments.id = v_assignment;
  if v_verification <> 'live_timer' then
    raise exception 'Verifying a timed seva downgraded it to %.', v_verification;
  end if;

  -- A no-show cannot be verified into having happened.
  select acts.assignment_id into v_assignment
  from public.seva_pe_acts acts where acts.key = 'noshow';
  begin
    perform public.verify_seva_assignment(v_assignment);
    raise exception 'A no-show was verified.';
  exception when others then
    if position('not recorded as having served' in sqlerrm) = 0 then raise; end if;
  end;
end;
$$;

reset role;
select set_config('request.jwt.claim.sub', '', true);

-- The missing step, taken: what was awaiting_verification is now counted.
do $$
declare
  v_status text;
  v_quality numeric;
begin
  select acts.points_status, acts.quality into v_status, v_quality
  from public.seva_mala_acts() acts
  join public.seva_pe_acts ids on ids.assignment_id = acts.assignment_id
  where ids.key = 'selfsaid';

  if v_status <> 'counted' or v_quality <> 1.0 then
    raise exception
      'Once verified, the served and completed act reads % at quality %.', v_status, v_quality;
  end if;
end;
$$;

-- A seva that has not started yet cannot be verified into the past.
do $$
declare
  v_assignment uuid;
begin
  select assignments.id into v_assignment
  from public.service_assignments assignments
  join public.service_instances instances
    on instances.id = assignments.service_instance_id
  where instances.template_id is not null
    and instances.date > public.seva_mala_today()
  limit 1;

  if v_assignment is null then
    raise exception 'The generator produced no future weekly instance to test against.';
  end if;
end;
$$;

set local role authenticated;
select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'president'), true);

do $$
declare
  v_assignment uuid;
begin
  select assignments.id into v_assignment
  from public.service_assignments assignments
  join public.service_instances instances
    on instances.id = assignments.service_instance_id
  where instances.template_id is not null
    and instances.date > public.seva_mala_today()
  limit 1;

  begin
    perform public.verify_seva_assignment(v_assignment);
    raise exception 'A seva that has not happened yet was verified.';
  exception when others then
    if position('once it has started' in sqlerrm) = 0 then raise; end if;
  end;
end;
$$;

reset role;
select set_config('request.jwt.claim.sub', '', true);

-- ---------------------------------------------------------------------------
-- 11. Nothing here opened a door.
-- ---------------------------------------------------------------------------

set local role authenticated;
select set_config('request.jwt.claim.sub',
  (select ids.id::text from public.seva_pe_ids ids where ids.key = 'other'), true);

do $$
begin
  begin
    perform count(*) from public.period_scores;
    raise exception 'A devotee read period_scores.';
  exception when insufficient_privilege then null;
  end;

  begin
    perform count(*) from public.seva_mala_acts();
    raise exception 'A devotee called seva_mala_acts.';
  exception when insufficient_privilege then null;
  end;

  begin
    perform count(*) from public.app_settings;
    raise exception 'A devotee read the dials.';
  exception when insufficient_privilege then null;
  end;
end;
$$;

reset role;
select set_config('request.jwt.claim.sub', '', true);

do $$
begin
  raise notice 'all seva points eligibility checks passed';
end;
$$;

select 'seva points eligibility verification passed' as result;

rollback;
